

SCDF_VERSION="1.1.1.RELEASE"

export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL=http://api.dev.cfdev.sh
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG=pcfdev-org
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE=pcfdev-space
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN=dev.cfdev.sh
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_SERVICES=rabbit,redis
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME=admin
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD=admin
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION=true
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_MEMORY=512
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_DISK=512
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_BUILDPACK=java_buildpack_offline
export SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_ENABLE_RANDOM_APP_NAME_PREFIX=false
export MAVEN_OFFLINE=true

PROJ_DIR=$(cd `dirname $0`; pwd)
SCDF_DIR=$PROJ_DIR/scdf

SCDF_INSTALLER_URL=https://repo.spring.io/release/org/springframework/cloud/spring-cloud-dataflow-server-cloudfoundry/${SCDF_VERSION}/spring-cloud-dataflow-server-cloudfoundry-${SCDF_VERSION}.jar
SCDF_INSTALLER_JAR=${SCDF_DIR}/spring-cloud-dataflow-server-cloudfoundry-${SCDF_VERSION}.jar

[[ ! -d $SCDF_DIR ]] && mkdir -p $SCDF_DIR
[[ ! -f $SCDF_INSTALLER_JAR ]] && wget -O $SCDF_INSTALLER_JAR $SCDF_INSTALLER_URL

java -jar $SCDF_INSTALLER_JAR
