version: "3.7"
services:
  locator:
    build: locator
    hostname: locator
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "7575:7575"
    volumes:
      - locator-data:/data
  server:
    build: server
    deploy:
      resources:
        limits:
          memory: 2G
    ports:
      - "40404:40404"
      - "8888:8888"
    volumes:
      - server-data:/data
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "pivotal"
      POSTGRES_USER: "pivotal"
      POSTGRES_DB: "gemfire"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  locator-data:
  server-data:
  db-data:
