version: "3.7"
services:
  locator:
    build: locator
    hostname: locator
    environment:
      PUBLIC_IP: ${DOCKER_MACHINE_IP}
    ports:
      - "8080:8080"
      - "10334:10334"
      - "1099:1099"
      - "7070:7070"
    volumes:
      - locator-data:/data

  server:
    build: server
    environment:
      PUBLIC_IP: ${DOCKER_MACHINE_IP}
      LOCATORS: "locator[10334]"
    ports:
      - "40404:40404"
      - "8888:8080"
    volumes:
      - server-data:/data
  db:
    build: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "pivotal"
      POSTGRES_USER: "pivotal"
      POSTGRES_DB: "gemfire"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  locator-data:
  server-data:
  db-data:
